### ISSUE TITLE
Environment var APPWRITE_FUNCTION_PROJECT_ID odd content

### ISSUE THREAD

**Issue by roelvandenbranddvc** [appwrite/sdk-for-node#19]
I was trying to get the Project ID from the Environment var APPWRITE_FUNCTION_PROJECT_ID

But it returned this:
APPWRITE_FUNCTION_PROJECT_ID=APPWRITE_FUNCTION_PROJECT_ID=613**********

When I would only expect the key itself.

**Comment by PineappleIOnic** [comment]
What version of appwrite is this on?

**Comment by roelvandenbranddvc** [comment]
I think it was 0.10.0 and without the .net core support, but haven't reproduced it yet on a newer version. 

Was a NodeJS function on a Collection Create Item Event or something like that.

**Comment by eldadfux** [comment]
Closing this issue for now, we'll be happy to re-open it again once more info is available.
