### ISSUE TITLE
🐛 Bug Report: Cannot instantiate new client when using Typescript

### ISSUE THREAD

**Issue by DLesage25** [appwrite/sdk-for-node#22]
### 👟 Reproduction steps

1. Install `node-appwrite` in a new TS project and compile using `tsc` with the following `tsconfig.json`:
```
{
    "compilerOptions": {
      "module": "commonjs",
      "declaration": true,
      "removeComments": true,
      "emitDecoratorMetadata": true,
      "experimentalDecorators": true,
      "allowSyntheticDefaultImports": true,
      "target": "es2017",
      "sourceMap": true,
      "outDir": "./dist",
      "baseUrl": "./",
      "incremental": true,
      "skipLibCheck": true,
      "moduleResolution": "node",

    },
    "exclude": ["node_modules", "dist", "__tests__"]
  }
  
```
2. Run `node dist/src/index`, with index.ts being the following:
```
import sdk from "node-appwrite";

const client = new sdk.Client();
```

3. I get the following error message:
```
const client = new node_appwrite_1.default.Client();
                                           ^

TypeError: Cannot read property 'Client' of undefined
    at Object.<anonymous> (/Users/daniellesage/Github/krypto-backend-ts/dist/index.js:5:44)
```

### 👍 Expected behavior

I should be able to instantiate a new client.

### 👎 Actual Behavior

I get the following error message:

```
const client = new node_appwrite_1.default.Client();
                                           ^

TypeError: Cannot read property 'Client' of undefined
    at Object.<anonymous> (/Users/daniellesage/Github/krypto-backend-ts/dist/index.js:5:44)
```

### 🎲 Appwrite version

Version 0.10.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

Nothing in particular.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by llemire** [comment]
I have the same problem, I haven't found the cause, but as a workaround, you can import each classes you need individually instead of loading the whole package in a variable.

so instad of:
```typescript
import sdk from "node-appwrite"
const client = new sdk.Client();
```

use: 
```typescript
import { Client } from "node-appwrite"
const client = new Client();
```

**Comment by TorstenDittmann** [comment]
This is expected behaviour from TypeScript, you need to use @llemire workaround 👍🏻
