### ISSUE TITLE
🚀 Feature: Allow to send raw bytes to storage

### ISSUE THREAD

**Issue by Aviortheking** [appwrite/sdk-for-node#30]
### 🔖 Feature description

You should add the ability to send `Buffer`s using the `Storage.createFile` function.

### 🎤 Pitch

With the latest version we can't `Storage.createFile` with anything other than a FS access, but depending on the context sending a raw Buffer is way better than writing to a file and then after sending the same file, also some applications contexts don't have the FS access on nodeJS.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by TorstenDittmann** [comment]
I totally agree!

This change is a result of the SDK being able to do chunked uploads on big files. We would need to investigate on how to solve this 👍🏻

**Comment by lohanidamodar** [comment]
@Aviortheking Hey, a PR is being worked on that will allow more flexibility while uploading file. Do provide your feedback if you have any
https://github.com/appwrite/sdk-generator/pull/459

**Comment by lohanidamodar** [comment]
@Aviortheking The latest version should support this. If you have any issues feel free to reopen the issue.
