### ISSUE TITLE
📚 Documentation: storageCreateFile / server / node

### ISSUE THREAD

**Issue by Amerlander** [appwrite/sdk-for-node#32]
### 💭 Description

The documentation for `storageCreateFile` seems wrong: https://appwrite.io/docs/server/storage?sdk=nodejs-default#storageCreateFile

For the `file` parameter, there is only a string allowed:
https://github.com/appwrite/sdk-for-node/blob/4f021b92b6ddf5598d5d8c66c410b8056788d16c/lib/services/storage.js#L334
https://github.com/appwrite/sdk-for-node/blob/4f021b92b6ddf5598d5d8c66c410b8056788d16c/lib/services/storage.js#L340

The code Example and the description are claiming, that I can provide a binary file:
https://appwrite.io/docs/server/storage?sdk=nodejs-default#storageCreateFile
![image](https://user-images.githubusercontent.com/3764089/163678271-5ccf63fd-b437-432a-8f7e-82eae6822ab5.png)

![image](https://user-images.githubusercontent.com/3764089/163678210-105449ab-e695-47f6-af76-f1ae52c30391.png)

This *works* but is different from what is in the documentation):
```js
const filename = './tmp/1.jpg';
let promise = storage.createFile(BUCKET_ID, id, filename);
```

Following the documenttation, this should, but does not work (also is not giving any error, or I might have overseen them):
```js
const file = new File([uin8array], '1.jpg', {type: 'image/jpeg'})
let promise = storage.createFile(BUCKET_ID, id, file);
```
----
If I provide different things as `file` I get Type Errors, which are telling, that it would work to provide either a String or a Uint8Array. Both does not work:
```js
const url = 'https://sample.com/1.jpg'
const response = await fetch(url)
const image = await response.arrayBuffer();
const uin8array = new Uint8Array(image);
let promise = storage.createFile(BUCKET_ID, id, uin8array);
```
-> `TypeError [ERR_INVALID_ARG_VALUE]: The argument 'path' must be a string or Uint8Array without null bytes. Received Uint8Array(178056)`

```js
const url = 'https://sample.com/1.jpg'
const response = await fetch(url)
const image = await response.arrayBuffer();
const uin8array = new Uint8Array(image);
const imageString = new TextDecoder().decode(uin8array);
let promise = storage.createFile(BUCKET_ID, id, imageString);
```
->`TypeError [ERR_INVALID_ARG_VALUE]: The argument 'path' must be a string or Uint8Array without null bytes. Received '����\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00...'`

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by lohanidamodar** [comment]
@Amerlander thank you for pointing this out.

**Comment by gewenyu99** [comment]
Please assign this to me, I'll take a look today :)

**Comment by gepd** [comment]
Any news on this?
I'm having the same problem

**Comment by gewenyu99** [comment]
> Any news on this? I'm having the same problem

The PR was merged :) The examples will be updated. 

Thank you guys for pointing this out, and thank you for your pateince.

**Comment by gewenyu99** [comment]
Oops, this is old :) 

It's been merged!
