### ISSUE TITLE
🐛 Bug Report: Missing Typescript Types

### ISSUE THREAD

**Issue by yk-sgr** [appwrite/sdk-for-node#48]
### 👟 Reproduction steps

Use node-appwrite and compile Typescript to Javascript.

Basically the same problem as https://github.com/appwrite/sdk-for-node/issues/37

### 👍 Expected behavior

Export the missing classes: `Blob`,  `Response`

### 👎 Actual Behavior

```
❯ npm run compile

> compile
> tsc

node_modules/node-appwrite/index.d.ts:1797:27 - error TS2304: Cannot find name 'Blob'.

1797     static fromBlob(blob: Blob, filename: string): InputFile;
                               ~~~~

node_modules/node-appwrite/index.d.ts:2020:31 - error TS2304: Cannot find name 'Response'.

2020     deleteSessions(): Promise<Response>;
                                   ~~~~~~~~

node_modules/node-appwrite/index.d.ts:2056:47 - error TS2304: Cannot find name 'Response'.

2056     deleteSession(sessionId: string): Promise<Response>;
                                                   ~~~~~~~~
.
.
.


Found 20 errors in the same file, starting at: node_modules/node-appwrite/index.d.ts:1797
```

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

MacOS

### 🧱 Your Environment

node-appwrite: 8.1.0

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@yk-sgr thanks for raising this issue! 🙏🏼 We'll look into it soon!
