### ISSUE TITLE
🐛 Bug Report: Uncaught Exception on Storage#createFile

### ISSUE THREAD

**Issue by DriedSponge** [appwrite/sdk-for-node#50]
### 👟 Reproduction steps

When trying to upload a file using a bad API key, an uncaught exception is thrown.

```ts
client.setEndpoint(endpoint)
client.setProjectprojectid)
client.setKey(badkey)
const storage = new sdk.Storage(client);
try {
    const appFile = await storage.createFile("files",file.name,InputFile.fromPath(directory,file.name))
    return true;
}catch (e){
     console.log(e);
     return false;
}
```

### 👍 Expected behavior

I should be able to catch the exception my self in my own try/catch block. 
```ts
try {
    const appFile = await storage.createFile("files",file.name,InputFile.fromPath(directory,file.name))
    return true;
}catch (e){
     console.log(e);
     return false;
}
```

### 👎 Actual Behavior

It actually crashes the whole application, and spits out a stack trace.
```ts
C:\laragon\www\myfiles\node_modules\.pnpm\node-appwrite@8.1.0\node_modules\node-appwrite\lib\client.js:171
                        throw new AppwriteException(error.response.data.message, error.response.status, error.response.data.type, error.response.data);
                              ^

AppwriteException [Error]: The current user is not authorized to perform the requested action.
    at Client.call (C:\laragon\www\myfiles\node_modules\.pnpm\node-appwrite@8.1.0\node_modules\node-appwrite\lib\client.js:171:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async uploadChunk (C:\laragon\www\myfiles\node_modules\.pnpm\node-appwrite@8.1.0\node_modules\node-appwrite\lib\services\storage.js:371:24)
    at async Writable.<anonymous> (C:\laragon\www\myfiles\node_modules\.pnpm\node-appwrite@8.1.0\node_modules\node-appwrite\lib\services\storage.js:433:21) {
  code: 401,
  type: 'user_unauthorized',
  response: {
    message: 'The current user is not authorized to perform the requested action.',
    code: 401,
    type: 'user_unauthorized',
    version: '1.1.1'
  }
}

Node.js v17.2.0
ELIFECYCLE  Command failed with exit code 1.
```
 

### 🎲 Appwrite version

Version 1.1.1

### 💻 Operating system

Windows

### 🧱 Your Environment

N/A

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Looks like we may have assumed this would catch any errors:

https://github.com/appwrite/sdk-for-node/blob/0fac3f6cabdea457ca946040fb3ab2ac2dc6e2d2/lib/services/storage.js#L439-L441

I think the solution might be to add a try/catch here:

https://github.com/appwrite/sdk-for-node/blob/0fac3f6cabdea457ca946040fb3ab2ac2dc6e2d2/lib/services/storage.js#L431-L437

like:

```javascript
            writeStream.on("finish", async () => {
                if(currentChunkSize > 0) {
                    try {
                        await uploadChunk(true);
                    } catch (e) {
                        reject(e);
                    }
                }
                
                resolve(response);
            });
```

**Comment by stnguyen90** [comment]
@DriedSponge can we actually close this as a duplicate of https://github.com/appwrite/sdk-for-node/issues/45 and you can 👍🏼 the previous issue?

**Comment by DriedSponge** [comment]
> @DriedSponge can we actually close this as a duplicate of #45 and you can 👍🏼 the previous issue?

Alright I'll go ahead and do that. Thanks!
