### ISSUE TITLE
📚 Documentation: The license link in the README not working

### ISSUE THREAD

**Issue by iswarmondal** [appwrite/sdk-for-node#52]
### 💭 Description

The link where it says ["Please see the BSD-3-Clause license"](https://github.com/appwrite/sdk-for-node#license) is not working in the README file.
It's throwing a connection time out
![image](https://user-images.githubusercontent.com/73457704/209762801-1162f5fe-5e53-4a55-b245-4439fc1507af.png)

Here's the [link](https://raw.githubusercontent.com/appwrite/appwrite/master/LICENSE)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Atsurak** [comment]
issue might be with your internet connection the link is working properly please recheck

**Comment by iswarmondal** [comment]
Thanks, I am looking into the broken code of conduct link in the issues template

**Comment by stnguyen90** [comment]
Seems to be working now.
