### ISSUE TITLE
🚀 Feature: add new function called findDocument() to find a document by query

### ISSUE THREAD

**Issue by bill-zhanxg** [appwrite/sdk-for-node#57]
### 🔖 Feature description

Add a new function in the Database SDK called findDocument which uses listDocument to get the first returned document with Query.

### 🎤 Pitch

This feature can be used if you have an id for attitude such as a user_id attribute and don't want it to be the same as the document id.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by bill-zhanxg** [comment]
maybe something like
```ts
/**
     * List Documents
     * Get a list of all the user's documents in a given collection. You can use the query params to filter your results.
     * @param databaseId
     * @param collectionId
     * @param queries
     * @throws — {AppwriteException}
     */
	findDocument<Document extends Models.Document>(
		databaseId: string,
		collectionId: string,
		queries: string[],
	): Promise<Document> {
		return new Promise((resolve, reject) => {
			this.listDocuments(databaseId, collectionId, queries)
				.then((document) => {
					if (document.documents[0]) resolve(document);
					else throw new AppwriteException('Document not found');
				})
				.catch(reject);
		});
	}
```

**Comment by joeyouss** [comment]
Hi
As I can understand from this, you are looking to find a particular document in the list of documents. Currently, you can do this using loops and if you prefer changing the search parameters, you can use queries for you to filter, sort, and paginate results. 

I will keep this issue open as of now since we are very keen in considering feedbacks from our community
