### ISSUE TITLE
User (role: guests) missing scope (account)

### ISSUE THREAD

**Issue by Coder-Vasen** [appwrite/sdk-for-node#64]
I am new to appwrite environment. I am trying to create a simple sveltekit web app. With user login and logout. In sveltekit ecosystem it is very convenient to store the user session on event.locals. I tried to do so using this code.
````ts
export const handle: Handle = async function ({ event, resolve }) {
	event.locals.appwrite = awServerClient(); // returns the {appwrite: {auth: sdk.Users,  account:  sdk.Account}}

	event.locals.getSession = async () => {
		const session = await event.locals.appwrite.account.getSession('current');
		console.log(session);
		return session;
	};
	return await resolve(event);
};
`````

I am getting **User (role: guests) missing scope (account)** this error. Is there any way to store the user session on server side.

**Comment by stnguyen90** [comment]
@Coder-Vasen, thanks for creating this issue! 🙏🏼 Were you using the [web sdk](https://github.com/appwrite/sdk-for-web) or this node SDK?

The web sdk is meant to be used client side as the session won't persist when used server side. We plan to add better support for SSR, but, I would suggest not using SSR if you don't need it as it greatly complicates things.

**Comment by Muhammadamin787** [comment]
### @stnguyen90 Thank you, I read your message. I'm also getting a similar error. I'm sharing the code as additional info. It would be nice if there were any workarounds for this.

### I'm using `Appwrite` with `NextJS14` and trying to get current account with `node-appwrite`  but getting an error: 

`Error AppwriteException [Error]: app.[PROJECT_ID]@service.cloud.appwrite.io (role: applications) missing scope (account)`

### In appwrite.config.ts
```
import * as Appwrite from 'node-appwrite';

const client = new Appwrite.Client();

client.setEndpoint(String(process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT))
client.setProject(String(process.env.NEXT_PUBLIC_PROJECT_ID))
client.setKey(String(process.env.NEXT_PUBLIC_API_KEY))

const account = new Appwrite.Account(client);
export { account };
```

###  In layout.tsx which is the Server Component
```
const getDetails = async () => {
    try {
        const details = await account.get();
        console.log("Details:", details);
        return details;
    } catch (error) {
        console.error("Error:", error);
    }
};

getDetails()
```

**Comment by Coder-Vasen** [comment]
Getting account of signed in user on sever side requires jwt to tell server about the respective user. Upon every request you can get jwt which has been created on client side. Then make a new Appwrite node client like client.jwt(your users jwt). By this way you can get currently logged in user account. But this proceess might not be efficient coz... Jwt will expire after 15 min of creation.

**Comment by Muhammadamin787** [comment]
@Coder-Vasen Thanks, that's helpful. 
I'll make that layout client component and get the account, I think in that case today it is a good choice.
