### ISSUE TITLE
🐛 Bug Report: NodeJS server SDK doesn't accept any argument for 'default' for creating array attributes in a collection

### ISSUE THREAD

**Issue by algusarov** [appwrite/sdk-for-node#67]
### 👟 Reproduction steps

I'm using the latest version of node-appwrite (11.1.0) and have set up some scripts to set up my projects programmatically. Everything works fine besides creating array attributes, when I try this code:

`await db.createStringAttribute(databaseId, collectionId, 'media', 10000, false, '', true)`

it generates this exception:

`Cannot set default value for array attributes`
```
message: 'Cannot set default value for array attributes',
    code: 400,
    type: 'attribute_default_unsupported',
    version: '1.4.13'
```
And when I try to use any other value instead of empty string for a 'default value' parameter, SDK throws another error saying that only string with size 0 can be used as a parameter.

### 👍 Expected behavior

Attribute is created.

### 👎 Actual Behavior

Exception thrown.

### 🎲 Appwrite version

Version 0.10.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@algusarov, thanks for creating this issue! 🙏🏼 This is expected. The goal for setting a default is to not have nulls. This isn't a problem with arrays because they will never be null.

That said, you are more than welcome to add your thoughts to https://github.com/appwrite/console/issues/461 and add a 👍🏼
