### ISSUE TITLE
🐛 Bug Report: type `Document` need support for any property

### ISSUE THREAD

**Issue by PratikDev** [appwrite/sdk-for-node#69]
### 👟 Reproduction steps

```ts
import { Client, Databases, Users } from "node-appwrite";

const client = new Client();
const databases = new Databases(client);

client
  .setEndpoint(ENDPOINT)
  .setProject(PROJECT_ID)
  .setKey(API_KEY);

const {my_attribute} = databases.getDocument(DB_ID, COLLECTION_ID, DOCUMENT_ID);
```
In this example, `my_attribute` shows a TS error saying "**Property 'my_attribute' does not exist on type 'Document'**"

That's a quickie. I would be happy to help with this

### 👍 Expected behavior

It should adapt to any property I wanna use from the document

### 👎 Actual Behavior

Throws a TS error

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

`node-appwrite` v11.1.0

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
This shouldn't be a problem anymore
