### ISSUE TITLE
🐛 Bug Report: Query class is broken

### ISSUE THREAD

**Issue by eroo36** [appwrite/sdk-for-node#76]
### 👟 Reproduction steps

Using node-appwrite sdk version 12.0.0, databases, listDocument function with a query. The problem does not occur on node-appwrite version 11.1.1 with same code.

```ts
new Databases(client).listDocuments<Models.Document & Card>(
      this.databaseId,
      this.collectionId,
      [Query.equal('userId', userId)],
    );
 ```
 
[Same issue in forum from someone else](https://appwrite.io/threads/1217781223578140702)

### 👍 Expected behavior

Should return the list of documents

### 👎 Actual Behavior

Query.equals throws an error: 
```
Error: Invalid query: {"method":"equal","attribute":"userId","values":["65ead2450a70959d9de7"]}
```

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Windows

### 🧱 Your Environment

appwrite version 1.3.7 on debian server
nestjs local server with node-appwrite 12.0.0

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eroo36** [comment]
I am sticking with version 11.1.1 for now

**Comment by abnegate** [comment]
Hi @eroo36, this is expected, version 12.0.0 of the node SDK requires Appwrite 1.5
