### ISSUE TITLE
🐛 Bug Report: listDocuments only selects the first 25 documents

### ISSUE THREAD

**Issue by 0PandaDEV** [appwrite/sdk-for-node#89]
### 👟 Reproduction steps

- selfhosted appwrite database
- have more than 25 documents in a collection
- try to get them with listDocuments
- only get the first 25 even though there are more in the collection

### 👍 Expected behavior

get all documents

### 👎 Actual Behavior

Only get the first 25

![image](https://github.com/appwrite/sdk-for-node/assets/70103896/952985a6-5392-4790-839a-db38204be05f)

### 🎲 Appwrite version

Version 1.5.4

### 💻 Operating system

Linux

### 🧱 Your Environment

I use Cloudflare zero Trust to expose my appwrite instance to the public, Other than taht there are no modifications.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by 0PandaDEV** [comment]
Ok nevermind just found out about `Query.limit()` but how can i make it infinite

**Comment by PsionicGeek** [comment]
Hi @0PandaDEV , I came across this thread https://appwrite.io/threads/1125237221818110003 similar to yours.
Hope this helps
