### ISSUE TITLE
🐛 Bug Report: Property 'contains' does not exist on type 'typeof Query'.ts(2339)

### ISSUE THREAD

**Issue by yuvraj108c** [appwrite/sdk-for-node#90]
### 👟 Reproduction steps

import { Query } from "node-appwrite";

const query = [Query.contains("labels", "premium")]

### 👍 Expected behavior

Query should support `.contains` on typescript

### 👎 Actual Behavior

It doesn't support `.contains`, but works, so likely a missing typescript definition

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

"node-appwrite": "^12.0.1",
 "typescript": "^5"

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@yuvraj108c thanks for creating this issue! 🙏🏼 This should be fixed in the newer (13 and above) versions of the node SDK. If you're still having problems, please feel free to create a new issue.
