### ISSUE TITLE
📚 Documentation: I am using appwrite node.js sdk in next.js and i need to see the logs of the req sdk making from next.js to appwrite server 

### ISSUE THREAD

**Issue by albin-baby-2002** [appwrite/sdk-for-node#91]
### 💭 Description

So when making an api request in client side we can see it in network tab. similarly i need to see the api req made by the sdk in console or in some log files. I don't know is this a next.js question or appwrite question.

Sorry in advance if i am wasting your time and if this issue is already addressed.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Perhaps [this](https://nextjs.org/docs/app/api-reference/config/next-config-js/logging) will help? 

Otherwise searching online for server side logging in general might be helpful as this is outside the scope of Appwrite. As such, I'm going to close this issue.
