### ISSUE TITLE
🐛 Bug Report: Function parameters are missing from TypeScript definition

### ISSUE THREAD

**Issue by nickgatzoulis** [appwrite/sdk-for-node#98]
### 👟 Reproduction steps

1. Use `appwrite init function` to create a Bun function or clone the Bun starter template `https://github.com/appwrite/templates/tree/main/bun/starter`
2. Observe that `{ req, res, log, error }: any` destructured params are of type `any`

### 👍 Expected behavior

There should be proper TypeScript typing for all four destructured parameters: `req`, `res`, `log` and `error`.

### 👎 Actual Behavior

There are no type definitions for any of the parameters.

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

MacOS

### 🧱 Your Environment

v1.16.1

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@nickgatzoulis, thanks for raising this issue. This looks like the same request as https://github.com/appwrite/appwrite/issues/7146, but for node. To consolidate, it would be best if you added a 👍🏼 to that issue.

And for the meantime, you can see the details of what's in the context [here](https://github.com/open-runtimes/open-runtimes/blob/62b17729041d9aa2669f0a4c908b4e1013c41b77/runtimes/node/versions/latest/src/server.js#L95-L164). Then you can define the types yourself.
